set -e
cmake -G "Ninja" -B ${ZKLLVM_BUILD:-build} -DCMAKE_BUILD_TYPE=Release -DCIRCUIT_ASSEMBLY_OUTPUT=TRUE -DBUILD_TESTS=True -DGENERATE_EVM_VERIFIER=TRUE -DCOMPONENT_SELECTOR_COLUMNS=50 .
ninja -C ${ZKLLVM_BUILD:-build} assigner recursive_gen  -j4
cmake -G "Ninja" -B ${ZKLLVM_BUILD:-build_recursive} -DCMAKE_BUILD_TYPE=Release -DCIRCUIT_ASSEMBLY_OUTPUT=TRUE -DBUILD_TESTS=True -DGENERATE_EVM_VERIFIER=TRUE -DCOMPONENT_SELECTOR_COLUMNS=60 -DLOOKUP_CONSTANT_COLUMNS=0 -DLOOKUP_SELECTOR_COLUMNS=0 .
ninja -C ${ZKLLVM_BUILD:-build_recursive} assigner  -j4